# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: ^ipython_notebooks/*
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.5.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-docstring-first
    exclude: 'apps'
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: check-symlinks
  - id: mixed-line-ending
  - id: fix-encoding-pragma
    args: ['--remove']
  - id: check-toml
  - id: debug-statements
# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v0.761
#     hooks:
#     -   id: mypy
- repo: https://github.com/saily/pre-commit-yapf-isort
  rev: 598ff67cc598dddee43bc611d0bf4a07f4b08619
  hooks:
  - id: yapf-isort
# - repo: https://github.com/darcamo/version_check_hook.git
#   rev: v1.0
#   hooks:
#   - id: version_check
# # Currently darglint is slow and thus this might be commented out in the future
# -   repo: https://github.com/terrencepreilly/darglint
#     rev: master
#     hooks:
#     - id: darglint
